### ISSUE TITLE
ddshow fails if TIMELY_WORKER_LOG_ADDR is set in ddshow's env

### ISSUE THREAD

**Issue by dtolnay** [Kixiron/ddshow#7]
The readme admittedly does say TIMELY_WORKER_LOG_ADDR is supposed to be set for the target program (as opposed to for ddshow). But if it is set for both, the result is ddshow crashes the target program, which seems unfortunate.

```console
$ export TIMELY_WORKER_LOG_ADDR=127.0.0.1:51317
$ target/release/ddshow 
[1s] Waiting for 1 connection on 127.0.0.1:51317: connected to 1 trace source
Press enter to finish collecting trace data (this will crash the source computation if it's currently running and cause data to not be fully processed)...thread 'timely:work-0' panicked at 'Could not connect logging stream to: "127.0.0.1:51317"', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/timely-0.12.0/src/execute.rs:280:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```console
$ export TIMELY_WORKER_LOG_ADDR=127.0.0.1:51317
$ target/release/timely_test 
thread 'timely:work-0' panicked at 'Event abomonation/write failed: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/timely-0.12.0/src/dataflow/operators/capture/event.rs:140:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'timely:work-0' panicked at 'Event abomonation/write failed: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/timely-0.12.0/src/dataflow/operators/capture/event.rs:140:70
stack backtrace:
   0:     0x55c8ab7f1f02 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55c8ab7f1f02 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c8ab7f1f02 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c8ab7f1f02 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55c8ab7408dc - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/core/src/fmt/mod.rs:1110:17
   5:     0x55c8ab7ee885 - std::io::Write::write_fmt::heb07fc0616bbd06d
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/io/mod.rs:1640:15
   6:     0x55c8ab7f3bfb - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55c8ab7f3bfb - std::sys_common::backtrace::print::h4fb679ac439362ea
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55c8ab7f3bfb - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/panicking.rs:208:50
   9:     0x55c8ab7f450c - std::panicking::default_hook::hb25822b45f6fdc4e
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/panicking.rs:225:9
  10:     0x55c8ab7f450c - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/panicking.rs:622:17
  11:     0x55c8ab7f3d6a - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/panicking.rs:519:13
  12:     0x55c8ab7f238c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55c8ab7f3cdd - rust_begin_unwind
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/panicking.rs:515:5
  14:     0x55c8ab5f8951 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/core/src/panicking.rs:92:14
  15:     0x55c8ab5f8a43 - core::result::unwrap_failed::hf79563fef9d11ab8
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/core/src/result.rs:1355:5
  16:     0x55c8ab67d57e - <timely::dataflow::operators::capture::event::binary::EventWriter<T,D,W> as timely::dataflow::operators::capture::event::EventPusher<T,D>>::push::h79ed4662796f3a42
  17:     0x55c8ab6824d7 - timely::logging::BatchLogger<T,E,P>::publish_batch::hefb22ff72491367b
  18:     0x55c8ab629e98 - <timely_logging::Logger<T,E> as timely_logging::Flush>::flush::h8e669a79068c3f5e
  19:     0x55c8ab7249a2 - core::ptr::drop_in_place<timely_logging::Logger<timely::logging::TimelyEvent,usize>>::heee7345d7759d1ab
  20:     0x55c8ab6fe0b8 - core::ptr::drop_in_place<core::cell::UnsafeCell<timely::progress::subgraph::SubgraphBuilder<(),usize>>>::h050c9c5f30c0bea9
  21:     0x55c8ab6ca600 - timely::worker::Worker<A>::dataflow::h08d459fe68cbd868
  22:     0x55c8ab6b08c9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h86d2f85671b8fe4b
  23:     0x55c8ab6f95d5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6124a11eda510dbe
  24:     0x55c8ab7f87d7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd1f9b751a68dd2ac
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/alloc/src/boxed.rs:1575:9
  25:     0x55c8ab7f87d7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h22d732940e85619f
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/alloc/src/boxed.rs:1575:9
  26:     0x55c8ab7f87d7 - std::sys::unix::thread::Thread::new::thread_start::h04c7a9e17ed1032c
                               at /rustc/150fad30ea25e812d481a784d02c95d3394b234b/library/std/src/sys/unix/thread.rs:71:17
  27:     0x7efc8f2ba609 - start_thread
  28:     0x7efc8f1db293 - clone
  29:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

**Comment by Kixiron** [comment]
Could you try this with master, I think I've fixed this in unreleased versions

**Comment by dtolnay** [comment]
Still present in master. The above output is current as of 5959faf06091f126cee64aff930082eff8544157.

**Comment by Kixiron** [comment]
That's really weird, I'll look into it. Thanks for reporting this!

**Comment by Kixiron** [comment]
That was a really sneaky one, but I think I fixed it if you can try master again.

Here's the breakdown:
I was using `timely::execute()` to spin up my dataflows, but it turns out that `timely::execute()` [unconditionally sets a logging hook for `TIMELY_WORKER_ADDR`](https://docs.rs/timely/0.12.0/src/timely/execute.rs.html#265-282) so that even though I [tried to un-set hooks to prevent this](https://github.com/Kixiron/ddshow/blob/master/src/dataflow/worker.rs#L59-L60) it didn't matter since the automatic hook was set (and therefore tried to connect to the address) before that code had a chance to run. To fix it I had to drop down to [`timely::execute::execute_from()`](https://docs.rs/timely/0.12.0/timely/execute/fn.execute_from.html) which doesn't do anything in regards to automatically setting hooks (I hope)

**Comment by dtolnay** [comment]
Thanks, looks good.
